In [4]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [9]:
import numpy as np
scores=np.array([10,20,40,50,80,5,9,78])
print("array>50:",scores>20)

array>50: [False False  True  True  True False False  True]


In [11]:
import numpy as np
scores=np.array([10,20,40,50,80,5,9,78])
scores=np.where(scores>=50,"pass","fail")
print(scores)

['fail' 'fail' 'fail' 'pass' 'pass' 'fail' 'fail' 'pass']


In [14]:
import numpy as np
x=np.array([[1,2],[3,4]])
y=np.array([[5,6],[7,8]])
result=np.concatenate((x,y))
print(result)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [16]:
import numpy as np
x=np.array([[1,2],[3,4]])
y=np.array([[5,6],[7,8]])
print(x*y)

[[ 5 12]
 [21 32]]


In [19]:
import numpy as np
x=np.array([1,2])
y=np.array([5,6])
print(np.dot(x,y))

17


In [ ]:
import numpy as np
data=np.array([10,20,np.nan,40,50])

In [18]:
import numpy as np
x=np.array([[1,2],[3,4]])
y=np.array([[5,6],[7,8]])
print(x@y)

[[19 22]
 [43 50]]


In [15]:
import numpy as np
rng=np.random.default_rng(42)
print("random integer :",rng.integer(1,10,size=5))
print("random floats:",rng.random(5))
print("normal distribution:",rng.normal(size=5))

AttributeError: 'numpy.random._generator.Generator' object has no attribute 'integer'